stages:
  - build
  - release

build:
  stage: build
  image: node:14-alpine
  script:
  - npm install
  - npm run build
  - npm ci --only=production
  artifacts:
    paths:
    - node_modules
    - dist
    - package.json
    - package-lock.json
    - Dockerfile
  rules:
  - if: '$CI_COMMIT_REF_NAME == "main"'
    when: always
  - when: never

release:
  stage: release
  image: docker:20.10
  services:
  - docker:20.10-dind
  variables:
    GIT_STRATEGY: none
    IMAGE_TAG: $CI_REGISTRY_IMAGE:latest
  script:
  - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  - docker build -t $IMAGE_TAG .
  - docker push $IMAGE_TAG
  rules:
  - if: '$CI_COMMIT_REF_NAME == "main"'
    when: always
  - when: never
