stages:
  - build
  - release

build:
  stage: build
  image: node:14-alpine
  script:
  - npm install
  - npm run build
  - npm ci --only=production
  artifacts:
    paths:
    - node_modules
    - dist
    - package.json
    - package-lock.json
    - Dockerfile
  rules:
  - if: '$CI_COMMIT_REF_NAME == "main"'
    when: always
  - when: never

release:
  stage: release
  image: docker:20.10
  services:
  - docker:20.10-dind
  variables:
    GIT_STRATEGY: none
  script:
  - export APP_IMAGE=${CI_REGISTRY}/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}":"latest
  - docker login -u gitlab-ci-token -p ${CI_JOB_TOKEN} ${CI_REGISTRY}
  - docker build -t ${APP_IMAGE} .
  - docker push ${APP_IMAGE}
  rules:
  - if: '$CI_COMMIT_REF_NAME == "main"'
    when: always
  - when: never
